import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add lua2rtt cjson common include
inc = inc + [cwd]

# add lua2rtt cjson basic code
src = src + Glob('./*.c')

# add group to IDE project
objs = DefineGroup('lua2rtt_cjson', src, depend = ['LUA2RTT_USING_EXLIBS_CJSON'], CPPPATH = inc)

Return('objs')