Import('rtconfig')
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('lua2rtt', src, depend = ['PKG_USING_LUA2RTT'], CPPPATH = CPPPATH)

Return('group')
